[workspace]
resolver = "2"
members = [ 
   "entities",
   "server",
   "migration",
]

[profile.release]
opt-level = 'z'  # Optimize for size.
lto = true
panic = 'abort'
strip = true
codegen-units = 1