//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "adverts")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub title: String,
    pub content: String,
    pub published: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::users_adverts::Entity")]
    UsersAdverts,
}

impl Related<super::users_adverts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UsersAdverts.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        super::users_adverts::Relation::Users.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::users_adverts::Relation::Adverts.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
