//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

pub mod prelude;

pub mod adverts;
pub mod groups;
pub mod groups_permissions;
pub mod permissions;
pub mod users;
pub mod users_adverts;
pub mod users_groups;
