//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

pub use super::adverts::Entity as Adverts;
pub use super::groups::Entity as Groups;
pub use super::groups_permissions::Entity as GroupsPermissions;
pub use super::permissions::Entity as Permissions;
pub use super::users::Entity as Users;
pub use super::users_adverts::Entity as UsersAdverts;
pub use super::users_groups::Entity as UsersGroups;
